### PR TITLE
Filtering on refresh

### PR DESCRIPTION
**Pull request by vlasiak**
When a user reloads the page (F5) saved conditions should be applied.

### CODE REVIEW

**Comment by vlasiak** [comment]
@sergeyradkevich, bug was fixed. Only for verifying. You can see the changes [here](https://github.com/vlasiak/rails_tada/compare/20-a-user-can-search...22-filtering-on-refresh) if you want, as this branch was inherited from unmerged #20. [Staging server](http://search-after-refresh.herokuapp.com/).
Please don't merge it until #20 will have been merged.

**Comment by sergeyradkevich** [comment]
Thanks @vlasiak. Verified. Sure, let's merge the previous one once ready, then rebase this and merge.

**Comment by vlasiak** [comment]
@sergeyradkevich, ready for reviewing. [Staging server](http://search-after-refresh.herokuapp.com/).

**Comment by sergeyradkevich** [comment]
@vlasiak It doesn't work for me, the conditions are being disappeared after page refresh.

**Comment by vlasiak** [comment]
@sergeyradkevich,

> It doesn't work for me, the conditions are being disappeared after page refresh. 

I refresh a page on a staging server, containing the conditions and everything works fine. Could you please specify if you use `F5` or maybe `ctrl+F5` (in this case it doesn't save any cache).

**Comment by vlasiak** [comment]
@sergeyradkevich, do you use [this staging server](http://search-after-refresh.herokuapp.com/)?

**Comment by sergeyradkevich** [comment]
Yes, I used the link you've provided for the staging. Just F5 or refresh button of the browser. Tested again and the problem persists.

**Comment by vlasiak** [comment]
@sergeyradkevich, I've just tested it at home and found that the problem exists in Google Chrome Browser. Going to fix it tomorrow.

**Comment by sergeyradkevich** [comment]
@vlasiak Okay, thanks. 

Btw, I've tested on FF and observed that initially (just after page reload) all the data are being displayed, but a sec later (or less) other request is made to search. That is not how it suppose to be. I suggest to make one request, meaning that by default a search conditions are empty so all the data are being displayed. Once a user typed some filters, further refreshing and navigation should consider given search conditions.

**Comment by vlasiak** [comment]
@sergeyradkevich, updated. [Staging server](https://tada-project.herokuapp.com/).

**Pull request merged**
